version: '3.8'

services:
  user_service_prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TOKEN_REPO=${TOKEN_REPO}
    ports:
      - ${PORT}:${PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN_REPO: ${TOKEN_REPO}
